### ISSUE TITLE
panic in `testing` docker image on Raspberry Pi 4

### ISSUE THREAD

**Issue by TheRealMazur** [dani-garcia/vaultwarden#1998]
### Subject of the issue

When trying to run the `testing` docker image, there is a panic and the container stops:
```
~/vw-data $ docker run -i --name vaultwarden -p 8090:80 vaultwarden/server:testing
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                      Version 1.22.2-b4c95fb4                       |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

[INFO] No .env file found.

thread panicked while processing panic. aborting.
~/vw-data $
```

Latest image that I've found to be working is 
```
vaultwarden/server:testing@sha256:b1819c383ce7e086c115dc816ef5dc8ecb5e77ec647fee7dc052015c1e98b5e8
```
from https://github.com/dani-garcia/vaultwarden/runs/3549020743

The next run of `Release` workflow: https://github.com/dani-garcia/vaultwarden/runs/3549706175
produced the image
```
vaultwarden/server@sha256:49bda0a9f866a1a5cb7847332ddeabf03a0d9ca50d59ecc485a92ddbf88abdbc
```
that gives:
```
Digest: sha256:49bda0a9f866a1a5cb7847332ddeabf03a0d9ca50d59ecc485a92ddbf88abdbc
Status: Downloaded newer image for vaultwarden/server@sha256:49bda0a9f866a1a5cb7847332ddeabf03a0d9ca50d59ecc485a92ddbf88abdbc
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                      Version 1.22.2-d5ed2ce6                       |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

[INFO] No .env file found.

thread panicked while processing panic. aborting.
DEBU[0059] [hijack] End of stdout
```

### Deployment environment

* vaultwarden version:

* Install method: docker image

* Clients used: 

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:
More info on the hardware used:
```
$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03112
Serial		: 1000000016faaf92
Model		: Raspberry Pi 4 Model B Rev 1.2
```

### Steps to reproduce

```
docker --debug run --rm -it --name vaultwarden -e RUST_BACKTRACE=1 -e LOG_LEVEL=trace -p 8090:80 vaultwarden/server:testing

```

### Expected behaviour

Running vaultwarden container

### Actual behaviour

Container stops after panic

**Comment by BlackDex** [comment]
For me, on a RPi2b it does continue a bit further, but also fails:
```
[2021-09-26 17:38:46.565][panic][ERROR] thread 'job-scheduler' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `4`': library/std/src/sys/unix/thread.rs:217
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: vaultwarden::init_logging::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:628:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:521:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys_common/backtrace.rs:141:18
   6: rust_begin_unwind
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/panicking.rs:517:5
   7: core::panicking::panic_fmt
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/core/src/panicking.rs:103:14
   8: core::panicking::assert_failed_inner
   9: core::panicking::assert_failed
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/core/src/panicking.rs:141:5
  10: std::sys::unix::thread::Thread::sleep
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys/unix/thread.rs:217:21
      std::thread::sleep
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/thread/mod.rs:810:5
  11: vaultwarden::schedule_jobs::{{closure}}
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/ac2d9fc509e36d1b32513744adf58c34bcc4f43c/library/std/src/sys/unix/thread.rs:106:17
```

**Comment by BlackDex** [comment]
I'm currently testing if it is the bullseye vs buster or the building-process

**Comment by BlackDex** [comment]
Seems to be an issue with the bullseye images.
It doesn't matter if i build with buster and run on bullseye it still breaks.

Building with bullseye and running on buster isn't possible because of updated glibc versions.
So, i think we need to revert back to buster for the time being, since if i just buster for both building and the final image, it works just fine.

**Comment by dani-garcia** [comment]
The error is originated here:
https://github.com/rust-lang/rust/blob/c09d6374324ee23cb5a4fe738f74369717dd642d/library/std/src/sys/unix/thread.rs#L217

[libc::EINTR](https://docs.rs/libc/0.2.102/libc/constant.EINTR.html) has the value 4 mentioned in the assert panic, so it seems like the libc nanosleep is failing on bullseye. We should return to buster for both images for now.

**Comment by BlackDex** [comment]
A quick search on this EINTR 4 (Sigill) status and bullseye seems to be bugging more dockerized software like MongoDB and Gitlab.
