### ISSUE TITLE
Doesn't start up after update

### ISSUE THREAD

**Issue by GoliathLabs** [dani-garcia/vaultwarden#2482]
### Deployment environment

* vaultwarden version: 1.25.0

* Install method: docker image

* Clients used: 

* Reverse proxy and version:  traefik 2

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce

using my docker-compose.yml
### Actual behaviour

Doesn't start up. Log does show this
```
bitwarden-vaultwarden-1       | Error: Rocket configuration extraction from provider failed.
bitwarden-vaultwarden-1       |    >> invalid value string "off", expected true or false
bitwarden-vaultwarden-1       |    >> for key CLI_COLORS
bitwarden-vaultwarden-1       |    >> in `ROCKET_` environment variable(s)
bitwarden-vaultwarden-1       | thread 'main' panicked at 'aborting due to configuration error(s)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/config/config.rs:293:13
bitwarden-vaultwarden-1       | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bitwarden-vaultwarden-1       | thread 'main' panicked at 'aborting due to configuration error(s)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/config/config.rs:293:13
bitwarden-vaultwarden-1       | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bitwarden-vaultwarden-1       | Error: Rocket configuration extraction from provider failed.
bitwarden-vaultwarden-1       |    >> invalid value string "off", expected true or false
bitwarden-vaultwarden-1       |    >> for key CLI_COLORS
bitwarden-vaultwarden-1       |    >> in `ROCKET_` environment variable(s)
bitwarden-vaultwarden-1       | thread 'main' panicked at 'aborting due to configuration error(s)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.5.0-rc.2/src/config/config.rs:293:13
bitwarden-vaultwarden-1       | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
bitwarden-vaultwarden-1       | Error: Rocket configuration extraction from provider failed.
bitwarden-vaultwarden-1       |    >> invalid value string "off", expected true or false
bitwarden-vaultwarden-1       |    >> for key CLI_COLORS
bitwarden-vaultwarden-1       |    >> in `ROCKET_` environment variable(s)
bitwarden-vaultwarden-1       | Error: Rocket configuration extraction from provider failed.
bitwarden-vaultwarden-1       |    >> invalid value string "off", expected true or false
bitwarden-vaultwarden-1       |    >> for key CLI_COLORS
bitwarden-vaultwarden-1       |    >> in `ROCKET_` environment variable(s)
```

I did go back to 1.24.0 for the time being.

**Comment by dani-garcia** [comment]
Do you happen to have the `ROCKET_CLI_COLORS` env variable defined in the docker compose file? If so, that was for the older version of the Rocket web server and isn't needed anymore. We should probably unset it in code to avoid it crashing the server though.

**Comment by GoliathLabs** [comment]
It isn't set in the .env file

**Comment by GoliathLabs** [comment]
But I'll try with the new env.template
