### ISSUE TITLE
Cannot update to 1.25/26 from 1.24 (Kubernetes)

### ISSUE THREAD

**Issue by dan-m8t** [dani-garcia/vaultwarden#2865]
Hi,

I am using Vaultwarden in Kubernetes and wanted to update to the latest version.

When I bump the image version I'll receive an error and the pod fails to start.

Btw after I rolled back to 1.24 I get also an error but the pod is starting just fine. I'll post both errors.

1.24 (working as before):

```
[2022-10-25 22:54:02.056][panic][ERROR] thread 'job-scheduler' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Expression("Invalid cron expression.") }': src/main.rs:353
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
```

The error in 1.25 and 1.26 are the same, for example here's the log for 1.25.2

1.25.2:

```thread panicked while panicking. aborting.
[2022-10-25 22:58:49.632][panic][ERROR] thread 'job-scheduler' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Expression("Invalid cron expression.") }': src/main.rs:467
   0: vaultwarden::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: std::sys::unix::thread::Thread::new::thread_start

[2022-10-25 22:58:49.634][panic][ERROR] thread 'job-scheduler' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime': src/db/mod.rs:185
   0: vaultwarden::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_display
   7: tokio::runtime::handle::Handle::current
   8: tokio::runtime::blocking::pool::spawn_blocking
   9: core::ptr::drop_in_place<vaultwarden::db::DbPool>
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::unix::thread::Thread::new::thread_start
```

Any hint?

Thanks

Dan

**Comment by stefan0xC** [comment]
The error message `Invalid cron expression` points to a misconfigured `_SCHEDULE` value. My guess is that you are probably missing a ` *`. The expression must have 6 or 7 values.
