### ISSUE TITLE
Unknown Kdf - Webvault Version 2022.12.0

### ISSUE THREAD

**Issue by Cameo007** [dani-garcia/vaultwarden#3442]
I wanted to login to my web vault but after  entering my password I saw the error message "Unknown Kdf" so I couldn't login. The browser plugin, the desktop app (Windows) and the android app are working.

I can see these error messages in my browser's console:
```
Error: Unknown Kdf.
    at qo.<anonymous> (crypto.service.ts:422:13)
    at Generator.next (<anonymous>)
    at main.5f8690f5c03a207c390a.js:54:510166
    at new t (zone.js:1351:25)
    at So (main.5f8690f5c03a207c390a.js:54:509911)
    at qo.makeKey (main.5f8690f5c03a207c390a.js:54:517260)
    at useClass.<anonymous> (auth.service.ts:262:31)
    at Generator.next (<anonymous>)
    at r (main.5f8690f5c03a207c390a.js:54:403766)
    at t.invoke (zone.js:409:30)
```
and
```
Received API exception: Error: Unknown Kdf.
```

both from `consoleLog.service.ts:51`

**Comment by BlackDex** [comment]
Which version of Vaultwarden are you running, how did you installed it?
We need more info.

**Comment by BlackDex** [comment]
Ow, I see you have `web-vault` 2022.12.0. That is too old. Upgrade Vaultwarden to the latest version. That will solve your issues.
