### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by lesha-co** [dani-garcia/vaultwarden#5025]
### Vaultwarden Support String

n/a

### Vaultwarden Build Version

1.32.0 (and also `testing`)

### Deployment method

Official Container Image

### Custom deployment method

DigitalOcean App Platform

### Reverse Proxy

n/a

### Host/Server Operating System

Cloud

### Clients

Web Vault

### Client Version

n/a

### Steps To Reproduce

1. create a new managed database (I used supabase)
2. plug connection string to `DATABASE_URL` env variable
3. I also have added `PUSH_ENABLED`, `PUSH_INSTALLATION_ID`, `PUSH_INSTALLATION_KEY`
4. It starts up successfully, for now.
5. go to /#/register page
6. Somewhere around this time, it starts to log a lot of errors, in logs you can see several of them
7. try to restart the container, it won't ever come back, will error out

### Expected Result

successful startup

### Actual Result

see logs

### Logs

```text
[vaultwarden-server] [2024-10-02 22:39:38] [2024-10-02 22:39:38.011][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:39:38] [2024-10-02 22:39:38.014][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:39:38] [2024-10-02 22:39:38.017][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:16] [2024-10-02 22:40:16.452][request][INFO] GET /api/organizations/undefined/policies/token?token=undefined&email=undefine
[vaultwarden-server] [2024-10-02 22:40:16] [2024-10-02 22:40:16.457][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:16] [2024-10-02 22:40:16.461][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:16] [2024-10-02 22:40:16.465][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:16] [2024-10-02 22:40:16.468][response][INFO] (list_policies_token) GET /api/organizations/<org_id>/policies/token?<token> => 200 OK
[vaultwarden-server] [2024-10-02 22:40:20] [2024-10-02 22:40:20.291][request][INFO] GET /api/organizations/undefined/policies/token?token=undefined&email=undefine
[vaultwarden-server] [2024-10-02 22:40:20] [2024-10-02 22:40:20.296][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:20] [2024-10-02 22:40:20.303][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:20] [2024-10-02 22:40:20.309][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:20] [2024-10-02 22:40:20.312][response][INFO] (list_policies_token) GET /api/organizations/<org_id>/policies/token?<token> => 200 OK
[vaultwarden-server] [2024-10-02 22:40:38] [2024-10-02 22:40:38.015][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:38] [2024-10-02 22:40:38.021][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:40:38] [2024-10-02 22:40:38.027][panic][ERROR] thread 'tokio-runtime-worker' panicked at 'Error finding expired contexts in twofactor_duo_ctx: DatabaseError(Unknown, "prepared statement \"__diesel_stmt_3\" does not exist")': src/db/models/two_factor_duo_context.rs:61
[vaultwarden-server] [2024-10-02 22:40:38]    0: vaultwarden::init_logging::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    1: std::panicking::rust_panic_with_hook
[vaultwarden-server] [2024-10-02 22:40:38]    2: std::panicking::begin_panic_handler::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    3: std::sys_common::backtrace::__rust_end_short_backtrace
[vaultwarden-server] [2024-10-02 22:40:38]    4: rust_begin_unwind
[vaultwarden-server] [2024-10-02 22:40:38]    5: core::panicking::panic_fmt
[vaultwarden-server] [2024-10-02 22:40:38]    6: core::result::unwrap_failed
[vaultwarden-server] [2024-10-02 22:40:38]    7: vaultwarden::db::models::two_factor_duo_context::TwoFactorDuoContext::find_expired::{{closure}}::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    8: vaultwarden::api::core::two_factor::duo_oidc::purge_duo_contexts::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    9: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:40:38]   10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
[vaultwarden-server] [2024-10-02 22:40:38]   11: tokio::runtime::scheduler::multi_thread::worker::run
[vaultwarden-server] [2024-10-02 22:40:38]   12: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:40:38]   13: std::sys_common::backtrace::__rust_begin_short_backtrace
[vaultwarden-server] [2024-10-02 22:40:38]   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
[vaultwarden-server] [2024-10-02 22:40:38]   15: std::sys::pal::unix::thread::Thread::new::thread_start
[vaultwarden-server] [2024-10-02 22:40:38]   16: <unknown>
[vaultwarden-server] [2024-10-02 22:40:38]   17: <unknown>
[vaultwarden-server] [2024-10-02 22:40:38] 
[vaultwarden-server] [2024-10-02 22:40:38] [2024-10-02 22:40:38.034][panic][ERROR] thread 'tokio-runtime-worker' panicked at 'Error loading auth_requests: DatabaseError(Unknown, "incorrect binary data format in bind parameter 1")': src/db/models/auth_request.rs:126
[vaultwarden-server] [2024-10-02 22:40:38]    0: vaultwarden::init_logging::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    1: std::panicking::rust_panic_with_hook
[vaultwarden-server] [2024-10-02 22:40:38]    2: std::panicking::begin_panic_handler::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    3: std::sys_common::backtrace::__rust_end_short_backtrace
[vaultwarden-server] [2024-10-02 22:40:38]    4: rust_begin_unwind
[vaultwarden-server] [2024-10-02 22:40:38]    5: core::panicking::panic_fmt
[vaultwarden-server] [2024-10-02 22:40:38]    6: core::result::unwrap_failed
[vaultwarden-server] [2024-10-02 22:40:38]    7: vaultwarden::db::models::auth_request::AuthRequest::find_created_before::{{closure}}::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    8: vaultwarden::db::models::auth_request::AuthRequest::purge_expired_auth_requests::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]    9: vaultwarden::api::core::accounts::purge_auth_requests::{{closure}}
[vaultwarden-server] [2024-10-02 22:40:38]   10: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:40:38]   11: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
[vaultwarden-server] [2024-10-02 22:40:38]   12: tokio::runtime::scheduler::multi_thread::worker::run
[vaultwarden-server] [2024-10-02 22:40:38]   13: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:40:38]   14: std::sys_common::backtrace::__rust_begin_short_backtrace
[vaultwarden-server] [2024-10-02 22:40:38]   15: core::ops::function::FnOnce::call_once{{vtable.shim}}
[vaultwarden-server] [2024-10-02 22:40:38]   16: std::sys::pal::unix::thread::Thread::new::thread_start
[vaultwarden-server] [2024-10-02 22:40:38]   17: <unknown>
[vaultwarden-server] [2024-10-02 22:40:38]   18: <unknown>
[vaultwarden-server] [2024-10-02 22:40:38] 
[vaultwarden-server] [2024-10-02 22:41:38] [2024-10-02 22:41:38.017][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:41:38] [2024-10-02 22:41:38.020][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:41:38] [2024-10-02 22:41:38.027][panic][ERROR] thread 'tokio-runtime-worker' panicked at 'Error finding expired contexts in twofactor_duo_ctx: DatabaseError(Unknown, "prepared statement \"__diesel_stmt_3\" does not exist")': src/db/models/two_factor_duo_context.rs:61
[vaultwarden-server] [2024-10-02 22:41:38]    0: vaultwarden::init_logging::{{closure}}
[vaultwarden-server] [2024-10-02 22:41:38]    1: std::panicking::rust_panic_with_hook
[vaultwarden-server] [2024-10-02 22:41:38]    2: std::panicking::begin_panic_handler::{{closure}}
[vaultwarden-server] [2024-10-02 22:41:38]    3: std::sys_common::backtrace::__rust_end_short_backtrace
[vaultwarden-server] [2024-10-02 22:41:38]    4: rust_begin_unwind
[vaultwarden-server] [2024-10-02 22:41:38]    5: core::panicking::panic_fmt
[vaultwarden-server] [2024-10-02 22:41:38]    6: core::result::unwrap_failed
[vaultwarden-server] [2024-10-02 22:41:38]    7: vaultwarden::db::models::two_factor_duo_context::TwoFactorDuoContext::find_expired::{{closure}}::{{closure}}
[vaultwarden-server] [2024-10-02 22:41:38]    8: vaultwarden::api::core::two_factor::duo_oidc::purge_duo_contexts::{{closure}}
[vaultwarden-server] [2024-10-02 22:41:38]    9: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:41:38]   10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
[vaultwarden-server] [2024-10-02 22:41:38]   11: tokio::runtime::scheduler::multi_thread::worker::run
[vaultwarden-server] [2024-10-02 22:41:38]   12: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:41:38]   13: std::sys_common::backtrace::__rust_begin_short_backtrace
[vaultwarden-server] [2024-10-02 22:41:38]   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
[vaultwarden-server] [2024-10-02 22:41:38]   15: std::sys::pal::unix::thread::Thread::new::thread_start
[vaultwarden-server] [2024-10-02 22:41:38]   16: <unknown>
[vaultwarden-server] [2024-10-02 22:41:38]   17: <unknown>
[vaultwarden-server] [2024-10-02 22:41:38] 
[vaultwarden-server] [2024-10-02 22:42:38] [2024-10-02 22:42:38.020][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:42:38] [2024-10-02 22:42:38.022][r2d2][ERROR] prepared statement "__diesel_stmt_0" already exists
[vaultwarden-server] [2024-10-02 22:42:38] [2024-10-02 22:42:38.031][panic][ERROR] thread 'tokio-runtime-worker' panicked at 'Error loading auth_requests: DatabaseError(Unknown, "prepared statement \"__diesel_stmt_2\" does not exist")': src/db/models/auth_request.rs:126
[vaultwarden-server] [2024-10-02 22:42:38]    0: vaultwarden::init_logging::{{closure}}
[vaultwarden-server] [2024-10-02 22:42:38]    1: std::panicking::rust_panic_with_hook
[vaultwarden-server] [2024-10-02 22:42:38]    2: std::panicking::begin_panic_handler::{{closure}}
[vaultwarden-server] [2024-10-02 22:42:38]    3: std::sys_common::backtrace::__rust_end_short_backtrace
[vaultwarden-server] [2024-10-02 22:42:38]    4: rust_begin_unwind
[vaultwarden-server] [2024-10-02 22:42:38]    5: core::panicking::panic_fmt
[vaultwarden-server] [2024-10-02 22:42:38]    6: core::result::unwrap_failed
[vaultwarden-server] [2024-10-02 22:42:38]    7: vaultwarden::db::models::auth_request::AuthRequest::find_created_before::{{closure}}::{{closure}}
[vaultwarden-server] [2024-10-02 22:42:38]    8: vaultwarden::db::models::auth_request::AuthRequest::purge_expired_auth_requests::{{closure}}
[vaultwarden-server] [2024-10-02 22:42:38]    9: vaultwarden::api::core::accounts::purge_auth_requests::{{closure}}
[vaultwarden-server] [2024-10-02 22:42:38]   10: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:42:38]   11: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
[vaultwarden-server] [2024-10-02 22:42:38]   12: tokio::runtime::scheduler::multi_thread::worker::run
[vaultwarden-server] [2024-10-02 22:42:38]   13: tokio::runtime::task::raw::poll
[vaultwarden-server] [2024-10-02 22:42:38]   14: std::sys_common::backtrace::__rust_begin_short_backtrace
[vaultwarden-server] [2024-10-02 22:42:38]   15: core::ops::function::FnOnce::call_once{{vtable.shim}}
[vaultwarden-server] [2024-10-02 22:42:38]   16: std::sys::pal::unix::thread::Thread::new::thread_start
[vaultwarden-server] [2024-10-02 22:42:38]   17: <unknown>
[vaultwarden-server] [2024-10-02 22:42:38]   18: <unknown>
[vaultwarden-server] [2024-10-02 22:42:38] 
```
```


### Screenshots or Videos

_No response_

### Additional Context

_No response_

**Comment by lesha-co** [comment]
okay MAYBE I was too hasty with this because I can't reproduce this issue with a different database provider (DO itself)

this is still very strange and sadly $7 more expensive than before. I've used Supabase for last six months and this is first time I see an issue like this...

**Comment by BlackDex** [comment]
I do not know supabase, but it seems a Postgresql compatible database. That doesn't mean it's is fully compatible or might expect some queries to be done differently. Same goes for CockroachDB for example. It's is Postgresql compatible, but it is missing a few features which causes Vaultwarden to not work well with it.

We support the official Postgresql, SQLite, MariaDB and MySQL databases. Everything else is out of scope.
